import { expect, test, type Page } from '@playwright/test'
import { mkdirSync } from 'node:fs'

const output = 'artifacts/recording-sync'
mkdirSync(output, { recursive: true })
async function visit(page: Page, route: string) {
  await page.goto(`/#${route}`)
  await page.reload()
  await page.locator('.app-bar,.shell,.login-button').first().waitFor()
}
async function signIn(page: Page, identifier = '13800000028') {
  await visit(page, '/pages/auth/login')
  await page.locator('input').nth(0).fill(identifier)
  await page.locator('input').nth(1).fill('123456')
  await page.locator('.agreement .check').click()
  await page.locator('.login-button').click()
  await page.waitForURL(/shell\/index/)
}
async function capture(page: Page, name: string) {
  await page.screenshot({ path: `${output}/${page.viewportSize()?.width}-${name}.png` })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
}

test('home carousel remains visible and switches between its three slides', async ({ page }) => {
  await signIn(page)
  await expect(page.locator('.home-carousel')).toBeVisible()
  await expect(page.locator('.home-slide')).toHaveCount(3)
  const indicator = page.locator('.home-carousel-page')
  await expect(indicator).toContainText(/\/ 3/)
  const initialPage = await indicator.textContent()
  await expect.poll(() => indicator.textContent(), { timeout: 10_000 }).not.toBe(initialPage)
  await expect(page.locator('.home-slide.navigation')).toContainText('海图航点')
  await capture(page, 'home-carousel')
})

test('device home keeps the carousel and service entry prominent without a duplicate list entry', async ({ page }) => {
  await signIn(page, '13800002861')
  await expect(page.locator('.shell-brand')).toContainText('鲨鱼妹妹')
  const repairEntry = page.locator('uni-button').filter({ hasText: '故障报修' }).first()
  await expect(repairEntry).toBeVisible()
  await expect(page.locator('#overview-device-list')).toBeVisible()
  await expect(page.locator('.overview-all')).toHaveCount(0)
  await expect(page.locator('.category-tabs')).toHaveCount(0)
  const repair = await repairEntry.boundingBox()
  const carousel = await page.locator('.home-carousel').boundingBox()
  expect(carousel!.y).toBeLessThan(repair!.y)
  await expect(page.locator('.equipment').first()).toBeVisible()
  for (const viewport of [{ width:375, height:812 }, { width:390, height:844 }, { width:430, height:932 }, { width:1280, height:720 }]) {
    await page.setViewportSize(viewport)
    const priority = await repairEntry.boundingBox()
    const slider = await page.locator('.home-carousel').boundingBox()
    expect(slider!.y).toBeLessThan(priority!.y)
    expect(priority!.height).toBeGreaterThanOrEqual(40)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await capture(page, 'device-home')
  }
})

test('device health and Bluetooth connection remain distinct on the home card', async ({ page }) => {
  await signIn(page, '13800002861')
  await page.locator('.category-list uni-button').filter({ hasText: '海水淡化器' }).click()
  const card = page.locator('.equipment').filter({ hasText: '海水淡化器-02' })
  await expect(card.locator('.status-badge')).toHaveText('在线')
  await expect(card.locator('.equipment-status')).toHaveText('未连接')
  await capture(page, 'online-bluetooth-disconnected')
})

test('installation links resolve by device SN and parts retain their own SKU', async ({ page }) => {
  await signIn(page)
  await visit(page, '/pages/device/detail?id=dev-02&mode=manage')
  await expect(page.locator('.linked-business')).toContainText('尚未建立安装项目')
  await visit(page, '/pages/manage/form?entity=projects&id=pro-01&mode=detail')
  await expect(page.locator('.project-device')).toHaveCount(1)
  await expect(page.locator('.project-device')).toContainText('DL300020240101')
  await expect(page.locator('.project-device')).not.toContainText('SW200020240202')
  await page.locator('.project-tabs').getByText('售后记录', { exact: true }).click()
  await expect(page.locator('.project-panel')).toContainText('服务体验投诉')
  await expect(page.locator('.project-panel')).not.toContainText('申请跨区服务')
  await page.evaluate(() => {
    const raw = JSON.parse(localStorage.getItem('shark-sister-db-v1') || '{}')
    const db = raw.data || raw
    db.projects.find((item: { id: string }) => item.id === 'pro-01').installedMaterials.push({
      id: 'audit-part', catalogId: 'catalog-01', quantity: 1, status: 'installed', ticketId: 'ticket-01', at: '2026-09-21T10:00:00.000Z',
    })
    localStorage.setItem('shark-sister-db-v1', JSON.stringify(raw))
  })
  await page.reload()
  await page.locator('.project-tabs').getByText('物料', { exact: true }).click()
  await expect(page.locator('.project-material-history')).toContainText('物料编码 PCB-DL3')
  await expect(page.locator('.project-material-history')).toContainText('登记时间 2026-09-21 10:00')
  await expect(page.locator('.project-material-history')).not.toContainText('设备 SN')
  await capture(page, 'installation-part-sku')
})

test('recording workbench priority and the single material entry survive the redesign', async ({ page }) => {
  await signIn(page)
  await page.locator('.tab-item').filter({ hasText: '工作台' }).click()
  await expect(page.locator('.workspace-metrics')).toHaveCount(0)
  const queue = await page.locator('.workspace-queue').boundingBox()
  const shortcuts = await page.locator('.workspace-shortcuts').boundingBox()
  expect(queue!.y + queue!.height).toBeLessThanOrEqual(shortcuts!.y)
  await expect(page.locator('.queue-row')).toHaveCount(3)
  await expect(page.locator('.queue-status')).toHaveCount(3)
  await expect(page.getByText('等待当前节点处理')).toHaveCount(0)
  await capture(page, 'workbench')
  await page.locator('.todo-all').click()
  await expect(page).toHaveURL(/state=todo/)
  expect(await page.locator('.todo-center-row').count()).toBeGreaterThanOrEqual(4)
  await capture(page, 'todo-center')
  await visit(page, '/pages/shell/index?tab=workbench')
  await page.locator('.queue-row').filter({ hasText: '物料' }).click()
  await expect(page.locator('.app-bar .app-action.right')).toHaveCount(0)
  await expect(page.locator('.floating-add')).toHaveCount(1)
  const scroll = await page.locator('.entity-scroll').boundingBox()
  const footer = await page.locator('.business-create-footer').boundingBox()
  expect(scroll!.y + scroll!.height).toBeLessThanOrEqual(footer!.y + 1)
  await capture(page, 'materials')
  await page.locator('.floating-add').click()
  await expect(page.locator('.material-request-form')).toBeVisible()
})

test('dealer approval center combines parts and purchase approvals and purchasing opens records first', async ({ page }) => {
  await signIn(page)
  await page.locator('.tab-item').filter({ hasText: '工作台' }).click()
  await page.locator('.business-row').filter({ hasText: '审批中心' }).click()
  await expect(page.getByText('统一审批队列', { exact: true })).toBeVisible()
  await expect(page.locator('.approval-row').filter({ hasText: '物料申请' })).toHaveCount(1)
  await expect(page.locator('.approval-row').filter({ hasText: '采购审批' })).toHaveCount(1)
  await expect(page.locator('.approval-row')).toHaveCount(2)
  await capture(page, 'approval-center')

  await visit(page, '/pages/shell/index?tab=workbench')
  await page.locator('.workspace-shortcut').filter({ hasText: '设备与配件采购' }).click()
  await expect(page).toHaveURL(/entity=purchases(?!.*state=catalog)/)
  await expect(page.locator('.purchase-view-tabs uni-button').nth(1)).toHaveClass(/active/)
  await expect(page.locator('.entity-card')).toHaveCount(1)
  await capture(page, 'purchase-records-first')
  await page.locator('.purchase-view-tabs uni-button').first().click()
  await page.locator('.entity-card').first().locator('.stepper uni-button').last().click()
  await expect(page.locator('.purchase-cart-summary')).toContainText('已选商品')
  await page.locator('.purchase-cart-summary').click()
  await expect(page.locator('.purchase-selection-sheet')).toBeVisible()
  await expect(page.locator('.purchase-selection-row')).toHaveCount(1)
  await expect(page.locator('.purchase-selection-row')).toContainText('可用库存')
  await capture(page, 'purchase-selected-items')
})

test('platform review is read-only and transfer and purchase details retain business facts', async ({ page }) => {
  await signIn(page)
  await visit(page, '/pages/manage/list?entity=transfers')
  const transfer = page.locator('.entity-card').filter({ hasText: 'IC150020240505' })
  await expect(transfer).toContainText('IC-1500')
  await expect(transfer.getByText('驳回', { exact: true })).toHaveCount(0)
  await transfer.getByText('查看详情', { exact: true }).click()
  await expect(page.locator('.business-detail-facts')).toContainText('设备类型')
  await expect(page.locator('.business-detail-facts')).toContainText('IC-1500')
  await expect(page.locator('.platform-review-notice')).toContainText('等待后台审核')
  await expect(page.locator('.business-detail-actions').getByText('驳回申请', { exact: true })).toHaveCount(0)
  await capture(page, 'transfer-detail')
  await visit(page, '/pages/manage/list?entity=purchases&state=record-detail&id=buy-01')
  await expect(page.locator('.business-detail-heading .status')).toContainText('待销售确认')
  await expect(page.locator('.purchase-detail-total')).toContainText('1,280.00')
  expect(await page.locator('.purchase-detail-total > strong').evaluate(element => element.getBoundingClientRect().height)).toBeLessThanOrEqual(35)
  await expect(page.locator('.business-line-item')).toContainText('单价 ¥640.00')
  await expect(page.locator('.business-line-item')).toContainText('1,280.00')
  await capture(page, 'purchase-detail')
})

test('report totals reconcile with outlet rows and year selection shows a genuine empty state', async ({ page }) => {
  await signIn(page)
  await visit(page, '/pages/process/index?scenario=dealerAnalytics')
  await expect(page.locator('.annual-overview')).toContainText('65,400')
  const serviceCount = Number(await page.locator('.annual-overview > uni-view').nth(1).locator('strong').innerText())
  const counts = await page.locator('.analytics-list [data-count]').evaluateAll(rows => rows.map(row => Number(row.getAttribute('data-count'))))
  expect(counts.reduce((sum, count) => sum + count, 0)).toBe(serviceCount)
  await page.locator('.analytics-month-strip uni-button').nth(7).click()
  await expect(page.locator('.analytics-month-detail')).toContainText('8月')
  await capture(page, 'analytics')
  await page.locator('.app-action.right').click()
  await expect(page.locator('.action-sheet')).toBeVisible()
  await capture(page, 'year-picker')
  await page.locator('.sheet-option').filter({ hasText: '2025' }).click()
  await expect(page.locator('.analytics-period')).toContainText('2025')
  await expect(page.getByText('本年度暂无销售或售后记录', { exact: true })).toBeVisible()
  await expect(page.locator('.line-chart')).toHaveCount(0)
  await expect(page.locator('.analytics-list')).toHaveCount(0)
  await capture(page, 'analytics-empty')
})

test('recording device summary and touch targets fit mobile and short desktop layouts', async ({ page }) => {
  await signIn(page)
  await visit(page, '/pages/device/detail?id=dev-01')
  await expect(page.locator('.command-feedback')).toHaveCount(0)
  await expect(page.locator('.remote-pad')).toHaveCount(0)
  await page.locator('.dock-propeller-button').click()
  await expect(page.getByText(/指令执行中|指令执行成功/).last()).toBeVisible()
  await capture(page, 'device-command-toast')
  await expect(page.locator('.command-feedback')).toHaveCount(0)
  await expect(page.locator('[data-metric-key="runtime"]')).toContainText('累计运行')
  await expect(page.locator('[data-metric-key="gear"]')).toBeVisible()
  await expect(page.locator('[data-metric-key="offset"]')).toBeVisible()
  await expect(page.locator('.chart-viewport [data-heading-compass]')).toHaveCount(0)
  await expect(page.locator('.helm-dock [data-heading-compass]')).toContainText('前')
  await expect(page.locator('.helm-dock [data-heading-compass]')).toContainText('后')
  await expect(page.locator('.helm-dock [data-heading-compass]')).toContainText('左')
  await expect(page.locator('.helm-dock [data-heading-compass]')).toContainText('右')
  await expect(page.locator('.heading-pointer')).toHaveAttribute('style', /rotate\(130deg\)/)
  await expect(page.locator('.dock-propeller-button')).toBeVisible()
  await expect(page.locator('.position-readout')).toHaveCount(0)
  await expect(page.locator('.secondary-telemetry')).toHaveCount(0)
  await expect(page.locator('[data-action-key="steer-left"]')).toBeVisible()
  await expect(page.locator('[data-action-key="steer-right"]')).toBeVisible()
  for (const viewport of [{ width:375, height:812 }, { width:390, height:844 }, { width:430, height:932 }, { width:1280, height:720 }]) {
    await page.setViewportSize(viewport)
    for (const selector of ['[data-action-key="steer-left"]', '[data-action-key="steer-right"]', '.connection-button', '.lift-up', '.lift-down', '.dock-propeller-button']) {
      const box = await page.locator(selector).first().boundingBox()
      expect(box!.height, selector).toBeGreaterThanOrEqual(44)
      expect(box!.width, selector).toBeGreaterThanOrEqual(44)
    }
    const top = await page.locator('.helm-top-stack').boundingBox()
    const tools = await page.locator('.chart-interactions').boundingBox()
    const dock = await page.locator('.helm-dock').boundingBox()
    expect(top!.y + top!.height).toBeLessThanOrEqual(tools!.y + 1)
    expect(tools!.y + tools!.height).toBeLessThanOrEqual(dock!.y + 1)
    expect(dock!.height).toBeLessThanOrEqual(150)
    const map = await page.locator('.helm-map').boundingBox()
    const effectiveMapHeight = dock!.y - (top!.y + top!.height)
    expect(effectiveMapHeight / map!.height).toBeGreaterThanOrEqual(.55)
    const waypoint = await page.locator('.waypoint-primary').boundingBox()
    const zoom = await page.locator('.zoom-control').boundingBox()
    const intersects = waypoint!.x < zoom!.x + zoom!.width && zoom!.x < waypoint!.x + waypoint!.width && waypoint!.y < zoom!.y + zoom!.height && zoom!.y < waypoint!.y + waypoint!.height
    expect(intersects).toBe(false)
    await capture(page, 'device')
  }
  await page.locator('[data-action-key="steer-left"]').click()
  await expect.poll(() => page.evaluate(() => {
    const raw = JSON.parse(localStorage.getItem('shark-sister-db-v1') || '{}')
    const db = raw?.type === 'object' && raw?.data ? raw.data : raw
    return db.devices?.find((item: { id: string }) => item.id === 'dev-01')?.controlState?.direction
  })).toBe('left')
  await page.locator('[data-action-key="steer-right"]').click()
  await expect.poll(() => page.evaluate(() => {
    const raw = JSON.parse(localStorage.getItem('shark-sister-db-v1') || '{}')
    const db = raw?.type === 'object' && raw?.data ? raw.data : raw
    return db.devices?.find((item: { id: string }) => item.id === 'dev-01')?.controlState?.direction
  })).toBe('right')
  await page.locator('[data-action-key="mode-selector"]').click()
  await page.locator('.mode-list uni-button').filter({ hasText: '航向锁定' }).click()
  await expect(page.locator('.secondary-telemetry')).toContainText('目标航向')
  await page.locator('[data-action-key="mode-selector"]').click()
  await page.locator('.mode-list uni-button').filter({ hasText: '手动控制' }).click()
  await expect(page.locator('.manual-control-panel')).toBeVisible()
  await expect(page.locator('.manual-control-pad')).toBeVisible()
  for (const selector of ['.north-button', '.south-button', '.west-button', '.east-button', '.manual-control-pad .stop-button']) {
    const box = await page.locator(selector).boundingBox()
    expect(box!.height, selector).toBeGreaterThanOrEqual(44)
    expect(box!.width, selector).toBeGreaterThanOrEqual(44)
  }
  await capture(page, 'device-manual-control')
})
