// Generated by scripts/sync-assets.mjs. Do not edit manually.
export const iconTones = ["default","muted","disabled","inverse","brand","brand-strong","success","warning","warning-strong","danger","accent","offline","support"] as const
export type IconTone = typeof iconTones[number]
export const iconAssets = {
  "anchor": {
    "defaultTone": "warning",
    "tones": [
      "inverse",
      "warning",
      "accent"
    ]
  },
  "apple": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "arrow-down": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "arrow-left": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "arrow-right": {
    "defaultTone": "inverse",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand"
    ]
  },
  "arrow-up": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "badge-check": {
    "defaultTone": "brand",
    "tones": [
      "muted",
      "brand",
      "success"
    ]
  },
  "badge-dollar-sign": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "battery": {
    "defaultTone": "warning",
    "tones": [
      "warning"
    ]
  },
  "battery-charging": {
    "defaultTone": "warning",
    "tones": [
      "brand",
      "warning",
      "offline"
    ]
  },
  "battery-full": {
    "defaultTone": "warning",
    "tones": [
      "warning"
    ]
  },
  "battery-warning": {
    "defaultTone": "warning",
    "tones": [
      "warning"
    ]
  },
  "bell": {
    "defaultTone": "default",
    "tones": [
      "default",
      "brand"
    ]
  },
  "bell-ring": {
    "defaultTone": "default",
    "tones": [
      "default",
      "brand",
      "success"
    ]
  },
  "bluetooth": {
    "defaultTone": "inverse",
    "tones": [
      "default",
      "muted",
      "disabled",
      "inverse",
      "brand",
      "brand-strong"
    ]
  },
  "boxes": {
    "defaultTone": "brand",
    "tones": [
      "brand",
      "accent"
    ]
  },
  "briefcase-business": {
    "defaultTone": "support",
    "tones": [
      "inverse",
      "support"
    ]
  },
  "building-2": {
    "defaultTone": "inverse",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand",
      "brand-strong"
    ]
  },
  "calendar-check": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "calendar-days": {
    "defaultTone": "default",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "camera": {
    "defaultTone": "accent",
    "tones": [
      "default",
      "accent"
    ]
  },
  "chart-line": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "chart-no-axes-combined": {
    "defaultTone": "warning",
    "tones": [
      "brand",
      "warning"
    ]
  },
  "check": {
    "defaultTone": "success",
    "tones": [
      "default",
      "muted",
      "inverse",
      "success"
    ]
  },
  "check-circle-2": {
    "defaultTone": "success",
    "tones": [
      "default",
      "success"
    ]
  },
  "chevron-down": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "chevron-left": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "chevron-right": {
    "defaultTone": "disabled",
    "tones": [
      "default",
      "muted",
      "disabled",
      "inverse",
      "brand"
    ]
  },
  "circle-alert": {
    "defaultTone": "danger",
    "tones": [
      "warning",
      "danger"
    ]
  },
  "circle-check": {
    "defaultTone": "success",
    "tones": [
      "default",
      "brand",
      "success"
    ]
  },
  "circle-help": {
    "defaultTone": "default",
    "tones": [
      "default",
      "accent"
    ]
  },
  "circle-pause": {
    "defaultTone": "danger",
    "tones": [
      "danger"
    ]
  },
  "circle-x": {
    "defaultTone": "danger",
    "tones": [
      "default",
      "danger"
    ]
  },
  "circuit-board": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "clipboard-check": {
    "defaultTone": "warning",
    "tones": [
      "default",
      "warning"
    ]
  },
  "clipboard-clock": {
    "defaultTone": "warning",
    "tones": [
      "warning"
    ]
  },
  "clock-3": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "muted",
      "brand",
      "success"
    ]
  },
  "cloud": {
    "defaultTone": "muted",
    "tones": [
      "muted",
      "inverse",
      "brand"
    ]
  },
  "cloud-upload": {
    "defaultTone": "warning",
    "tones": [
      "brand",
      "success",
      "warning"
    ]
  },
  "copy": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "cpu": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand",
      "brand-strong"
    ]
  },
  "credit-card": {
    "defaultTone": "inverse",
    "tones": [
      "default",
      "inverse",
      "brand",
      "success"
    ]
  },
  "crosshair": {
    "defaultTone": "muted",
    "tones": [
      "muted"
    ]
  },
  "database": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "download": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "inverse",
      "brand",
      "brand-strong"
    ]
  },
  "droplets": {
    "defaultTone": "success",
    "tones": [
      "success"
    ]
  },
  "ellipsis": {
    "defaultTone": "default",
    "tones": [
      "default",
      "accent"
    ]
  },
  "eye": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted"
    ]
  },
  "fan": {
    "defaultTone": "brand",
    "tones": [
      "muted",
      "inverse",
      "brand",
      "warning"
    ]
  },
  "flag": {
    "defaultTone": "brand",
    "tones": [
      "brand",
      "warning"
    ]
  },
  "flashlight": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "folder-check": {
    "defaultTone": "muted",
    "tones": [
      "muted"
    ]
  },
  "folder-kanban": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "folder-plus": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand",
      "success"
    ]
  },
  "folder-search": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "folder-x": {
    "defaultTone": "danger",
    "tones": [
      "danger"
    ]
  },
  "forward": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "inverse"
    ]
  },
  "globe-2": {
    "defaultTone": "default",
    "tones": [
      "default",
      "brand"
    ]
  },
  "grip-vertical": {
    "defaultTone": "disabled",
    "tones": [
      "muted",
      "disabled"
    ]
  },
  "hash": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "headphones": {
    "defaultTone": "brand",
    "tones": [
      "brand",
      "accent"
    ]
  },
  "history": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand",
      "brand-strong"
    ]
  },
  "house": {
    "defaultTone": "muted",
    "tones": [
      "muted",
      "brand"
    ]
  },
  "image": {
    "defaultTone": "default",
    "tones": [
      "default",
      "brand"
    ]
  },
  "image-plus": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "inbox": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "info": {
    "defaultTone": "brand-strong",
    "tones": [
      "default",
      "brand",
      "brand-strong",
      "warning",
      "accent"
    ]
  },
  "key-round": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand",
      "brand-strong"
    ]
  },
  "keyboard": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "landmark": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "languages": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "layers-3": {
    "defaultTone": "default",
    "tones": [
      "default",
      "brand"
    ]
  },
  "link-2": {
    "defaultTone": "muted",
    "tones": [
      "muted"
    ]
  },
  "link-2-off": {
    "defaultTone": "warning",
    "tones": [
      "warning"
    ]
  },
  "list-filter": {
    "defaultTone": "default",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand"
    ]
  },
  "list-restart": {
    "defaultTone": "default",
    "tones": [
      "default",
      "brand-strong"
    ]
  },
  "loader-circle": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "disabled",
      "inverse",
      "brand"
    ]
  },
  "locate-fixed": {
    "defaultTone": "default",
    "tones": [
      "default",
      "muted",
      "inverse"
    ]
  },
  "lock-keyhole": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand",
      "warning"
    ]
  },
  "log-in": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "log-out": {
    "defaultTone": "brand",
    "tones": [
      "brand",
      "danger"
    ]
  },
  "mail": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "map": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "map-pin": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "muted",
      "brand",
      "success"
    ]
  },
  "map-pin-check": {
    "defaultTone": "success",
    "tones": [
      "success"
    ]
  },
  "map-pin-plus": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "map-pin-x": {
    "defaultTone": "danger",
    "tones": [
      "danger"
    ]
  },
  "map-pinned": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "megaphone": {
    "defaultTone": "accent",
    "tones": [
      "accent"
    ]
  },
  "message-circle": {
    "defaultTone": "default",
    "tones": [
      "default",
      "success"
    ]
  },
  "message-square-plus": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "message-square-text": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "message-square-warning": {
    "defaultTone": "danger",
    "tones": [
      "muted",
      "danger"
    ]
  },
  "messages-square": {
    "defaultTone": "brand",
    "tones": [
      "inverse",
      "brand"
    ]
  },
  "moon": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "navigation": {
    "defaultTone": "inverse",
    "tones": [
      "default",
      "inverse",
      "brand"
    ]
  },
  "network": {
    "defaultTone": "accent",
    "tones": [
      "accent"
    ]
  },
  "notebook-pen": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "brand"
    ]
  },
  "package": {
    "defaultTone": "success",
    "tones": [
      "default",
      "muted",
      "brand",
      "success"
    ]
  },
  "package-check": {
    "defaultTone": "success",
    "tones": [
      "default",
      "success",
      "warning"
    ]
  },
  "package-plus": {
    "defaultTone": "muted",
    "tones": [
      "muted",
      "brand"
    ]
  },
  "package-search": {
    "defaultTone": "muted",
    "tones": [
      "muted",
      "accent"
    ]
  },
  "panels-top-left": {
    "defaultTone": "muted",
    "tones": [
      "muted",
      "brand"
    ]
  },
  "paperclip": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "pause": {
    "defaultTone": "default",
    "tones": [
      "default",
      "brand"
    ]
  },
  "pencil": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "phone": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand",
      "brand-strong"
    ]
  },
  "play": {
    "defaultTone": "success",
    "tones": [
      "default",
      "success"
    ]
  },
  "plus": {
    "defaultTone": "inverse",
    "tones": [
      "default",
      "inverse",
      "brand",
      "success"
    ]
  },
  "power": {
    "defaultTone": "success",
    "tones": [
      "inverse",
      "success"
    ]
  },
  "radio-tower": {
    "defaultTone": "success",
    "tones": [
      "brand",
      "success"
    ]
  },
  "refresh-ccw-dot": {
    "defaultTone": "warning",
    "tones": [
      "default",
      "warning",
      "accent"
    ]
  },
  "refresh-cw": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "inverse",
      "brand",
      "brand-strong",
      "warning-strong"
    ]
  },
  "rotate-cw": {
    "defaultTone": "inverse",
    "tones": [
      "inverse",
      "warning"
    ]
  },
  "route": {
    "defaultTone": "inverse",
    "tones": [
      "inverse",
      "brand"
    ]
  },
  "ruler": {
    "defaultTone": "brand",
    "tones": [
      "muted",
      "brand"
    ]
  },
  "save": {
    "defaultTone": "inverse",
    "tones": [
      "inverse"
    ]
  },
  "scan-line": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "search": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "inverse"
    ]
  },
  "send": {
    "defaultTone": "inverse",
    "tones": [
      "inverse"
    ]
  },
  "settings": {
    "defaultTone": "default",
    "tones": [
      "default",
      "brand",
      "accent"
    ]
  },
  "settings-2": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "share-2": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "shield-alert": {
    "defaultTone": "warning",
    "tones": [
      "default",
      "brand",
      "warning",
      "warning-strong"
    ]
  },
  "shield-check": {
    "defaultTone": "brand-strong",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand",
      "brand-strong",
      "success",
      "accent"
    ]
  },
  "ship": {
    "defaultTone": "muted",
    "tones": [
      "muted"
    ]
  },
  "ship-wheel": {
    "defaultTone": "inverse",
    "tones": [
      "default",
      "inverse",
      "brand"
    ]
  },
  "shopping-cart": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "inverse",
      "brand"
    ]
  },
  "shuffle": {
    "defaultTone": "accent",
    "tones": [
      "inverse",
      "brand",
      "warning",
      "warning-strong",
      "accent"
    ]
  },
  "smartphone": {
    "defaultTone": "inverse",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand",
      "brand-strong"
    ]
  },
  "snowflake": {
    "defaultTone": "brand",
    "tones": [
      "brand"
    ]
  },
  "square": {
    "defaultTone": "danger",
    "tones": [
      "danger"
    ]
  },
  "store": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand",
      "success",
      "warning",
      "accent"
    ]
  },
  "thermometer": {
    "defaultTone": "warning",
    "tones": [
      "default",
      "warning"
    ]
  },
  "timer-off": {
    "defaultTone": "danger",
    "tones": [
      "danger"
    ]
  },
  "trash-2": {
    "defaultTone": "danger",
    "tones": [
      "default",
      "danger"
    ]
  },
  "triangle-alert": {
    "defaultTone": "warning",
    "tones": [
      "default",
      "muted",
      "warning",
      "danger"
    ]
  },
  "truck": {
    "defaultTone": "success",
    "tones": [
      "brand-strong",
      "success"
    ]
  },
  "unlink": {
    "defaultTone": "danger",
    "tones": [
      "danger"
    ]
  },
  "unplug": {
    "defaultTone": "warning",
    "tones": [
      "default",
      "warning",
      "warning-strong"
    ]
  },
  "upload-cloud": {
    "defaultTone": "brand",
    "tones": [
      "default",
      "brand"
    ]
  },
  "user-plus": {
    "defaultTone": "default",
    "tones": [
      "default",
      "inverse",
      "brand"
    ]
  },
  "user-round": {
    "defaultTone": "muted",
    "tones": [
      "default",
      "muted",
      "inverse",
      "brand"
    ]
  },
  "users-round": {
    "defaultTone": "brand",
    "tones": [
      "brand",
      "accent"
    ]
  },
  "video": {
    "defaultTone": "default",
    "tones": [
      "default"
    ]
  },
  "wallet-cards": {
    "defaultTone": "accent",
    "tones": [
      "brand",
      "accent"
    ]
  },
  "warehouse": {
    "defaultTone": "brand",
    "tones": [
      "brand",
      "warning",
      "warning-strong",
      "accent"
    ]
  },
  "waves": {
    "defaultTone": "brand",
    "tones": [
      "inverse",
      "brand"
    ]
  },
  "wifi": {
    "defaultTone": "success",
    "tones": [
      "brand",
      "success"
    ]
  },
  "wifi-off": {
    "defaultTone": "warning",
    "tones": [
      "default",
      "brand",
      "warning"
    ]
  },
  "wrench": {
    "defaultTone": "warning",
    "tones": [
      "muted",
      "brand",
      "warning",
      "accent"
    ]
  },
  "x": {
    "defaultTone": "default",
    "tones": [
      "default",
      "muted",
      "inverse",
      "danger"
    ]
  }
} as const
export type IconName = keyof typeof iconAssets

const bundledIconAssets = import.meta.glob('../static/assest/icons/variants/*.png', { eager: true, import: 'default', query: '?url' }) as Record<string, string>
const bundledBrandAssets = import.meta.glob('../static/assest/brand/*.png', { eager: true, import: 'default', query: '?url' }) as Record<string, string>
const bundledBackgroundAssets = import.meta.glob('../static/assest/backgrounds/*.png', { eager: true, import: 'default', query: '?url' }) as Record<string, string>

export const brandAssets = {
  "logoGlyph": bundledBrandAssets['../static/assest/brand/logo-glyph.png'] || "/static/assest/brand/logo-glyph.png",
  "logoMark": bundledBrandAssets['../static/assest/brand/logo-mark.png'] || "/static/assest/brand/logo-mark.png"
} as const
export const backgroundAssets = {
  "authHeader": bundledBackgroundAssets['../static/assest/backgrounds/auth-header.png'] || "/static/assest/backgrounds/auth-header.png",
  "homeHero": bundledBackgroundAssets['../static/assest/backgrounds/home-hero.png'] || "/static/assest/backgrounds/home-hero.png",
  "mapGridTile": bundledBackgroundAssets['../static/assest/backgrounds/map-grid-tile.png'] || "/static/assest/backgrounds/map-grid-tile.png",
  "mapCanvas": bundledBackgroundAssets['../static/assest/backgrounds/map-canvas.png'] || "/static/assest/backgrounds/map-canvas.png",
  "profileHeader": bundledBackgroundAssets['../static/assest/backgrounds/profile-header.png'] || "/static/assest/backgrounds/profile-header.png",
  "splashBackground": bundledBackgroundAssets['../static/assest/backgrounds/splash-background.png'] || "/static/assest/backgrounds/splash-background.png"
} as const

export function resolveIconTone(name: string, tone?: IconTone): IconTone {
  const icon = iconAssets[name as IconName]
  if (!icon) return 'default'
  if (tone && (icon.tones as readonly string[]).includes(tone)) return tone
  if (!tone && (icon.tones as readonly string[]).includes('default')) return 'default'
  return icon.defaultTone
}

export function resolveIconAsset(name: string, tone?: IconTone): string {
  const icon = iconAssets[name as IconName]
  const fileName = icon ? `${name}--${resolveIconTone(name, tone)}.png` : 'circle-help--default.png'
  return bundledIconAssets[`../static/assest/icons/variants/${fileName}`] || `/static/assest/icons/variants/${fileName}`
}
