import type { Role } from '@/types/models'
import { designCaseRegistry } from './designCases'

export type RequirementStatus = 'complete-local' | 'simulated-local' | 'partial' | 'integration-required' | 'demo-exception' | 'source-blank' | 'missing'

export interface RequirementCase {
  sourceRow: number
  sourceSheet?: 'APP端功能列表'
  sourceText?: string
  requirement: string
  roles: Role[]
  route: string
  fields: string[]
  actions: string[]
  states: string[]
  evidence: string[]
  status: RequirementStatus
  uiCaseIds?: string[]
  uiAssertions?: string[]
  conclusion?: 'covered' | 'integration-required' | 'source-blank'
}

// Materialized from the V3.2 Excel sheet. Do not replace this with range-based completion flags.
export const v32RequirementCoverage: RequirementCase[] = [
  { sourceRow: 8, requirement: "账号系统 / 注册 / 邮箱注册\n（海外） / 邮箱 / 输入注册邮箱", roles: ["guest"], route: "/pages/auth/register?region=GLOBAL", fields: ["邮箱（文本输入框）"], actions: ["输入注册邮箱"], states: ["必填，邮箱格式校验", "前端正则校验，后端验证唯一性"], evidence: ["docx:table-row-008", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-008"], status: "complete-local" },
  { sourceRow: 9, requirement: "账号系统 / 注册 / 邮箱注册\n（海外） / 密码 / 设置登录密码", roles: ["guest"], route: "/pages/auth/register?region=GLOBAL", fields: ["密码（密码输入框）"], actions: ["设置登录密码"], states: ["8-20位，含字母和数字", "前端校验强度，后端加密存储"], evidence: ["docx:table-row-009", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-009"], status: "simulated-local" },
  { sourceRow: 10, requirement: "账号系统 / 注册 / 邮箱注册\n（海外） / 确认密码 / 再次输入密码", roles: ["guest"], route: "/pages/auth/register?region=GLOBAL", fields: ["确认密码（密码输入框）"], actions: ["再次输入密码"], states: ["需与密码一致", "前端校验两次输入一致"], evidence: ["docx:table-row-010", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-010"], status: "complete-local" },
  { sourceRow: 11, requirement: "账号系统 / 注册 / 邮箱注册\n（海外） / 邮箱验证码 / 输入邮件验证码", roles: ["guest"], route: "/pages/auth/register?region=GLOBAL", fields: ["邮箱验证码（输入框+按钮）"], actions: ["输入邮件验证码"], states: ["6位数字，60秒倒计时", "发送验证码到邮箱，缓存5分钟"], evidence: ["docx:table-row-011", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-011"], status: "simulated-local" },
  { sourceRow: 12, requirement: "账号系统 / 注册 / 邮箱注册\n（海外） / 注册按钮 / 提交注册", roles: ["guest"], route: "/pages/auth/register?region=GLOBAL", fields: ["注册按钮（按钮）"], actions: ["提交注册"], states: ["验证通过后完成注册", "调用注册接口，成功后自动登录跳转主页"], evidence: ["docx:table-row-012", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-012"], status: "complete-local" },
  { sourceRow: 13, requirement: "账号系统 / 注册 / Google一键注册\n（海外版） / Google授权 / Google账号一键注册并登录", roles: ["guest"], route: "/pages/auth/register?region=GLOBAL", fields: ["Google授权（第三方按钮）"], actions: ["Google账号一键注册并登录"], states: ["仅海外版显示，需Google服务", "调用Google OAuth2.0，获取用户信息自动创建账号"], evidence: ["docx:table-row-013", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-013"], status: "simulated-local" },
  { sourceRow: 14, requirement: "账号系统 / 注册 / 手机号注册\n（国内版） / 手机号 / 输入手机号", roles: ["guest"], route: "/pages/auth/register", fields: ["手机号（文本输入框）"], actions: ["输入手机号"], states: ["必填，11位格式", "验证格式和唯一性"], evidence: ["docx:table-row-014", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-014"], status: "complete-local" },
  { sourceRow: 15, requirement: "账号系统 / 注册 / 手机号注册\n（国内版） / 短信验证码 / 输入短信验证码", roles: ["guest"], route: "/pages/auth/register", fields: ["短信验证码（输入框+按钮）"], actions: ["输入短信验证码"], states: ["6位数字，60秒倒计时", "调用短信服务，缓存5分钟"], evidence: ["docx:table-row-015", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-015"], status: "simulated-local" },
  { sourceRow: 16, requirement: "账号系统 / 注册 / 微信注册\n（国内版） / 微信授权 / 微信一键注册", roles: ["guest"], route: "/pages/auth/register", fields: ["微信授权（第三方按钮）"], actions: ["微信一键注册"], states: ["仅国内版显示，注册后需绑定手机号", "调用微信SDK获取openid，引导绑定手机号"], evidence: ["docx:table-row-016", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-016"], status: "partial" },
  { sourceRow: 17, requirement: "账号系统 / 登录 / 代理商账号 / 账号激活 / 后台开通权限后首次登录", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/auth/password?mode=first", fields: ["账号激活（系统逻辑）"], actions: ["后台开通权限后首次登录"], states: ["首次登录强制修改密码", "后台创建账号分配角色，首次登录强制改密"], evidence: ["docx:table-row-017", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-017"], status: "complete-local" },
  { sourceRow: 18, requirement: "账号系统 / 登录 / 账号密码登录 / 账号 / 输入邮箱或手机号", roles: ["guest"], route: "/pages/auth/login", fields: ["账号（文本输入框）"], actions: ["输入邮箱或手机号"], states: ["必填", "支持邮箱/手机号两种方式"], evidence: ["docx:table-row-018", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-018"], status: "complete-local" },
  { sourceRow: 19, requirement: "账号系统 / 登录 / 账号密码登录 / 密码 / 输入登录密码", roles: ["guest"], route: "/pages/auth/login", fields: ["密码（密码输入框）"], actions: ["输入登录密码"], states: ["必填，密码隐藏", "加密比对数据库"], evidence: ["docx:table-row-019", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-019"], status: "simulated-local" },
  { sourceRow: 20, requirement: "账号系统 / 登录 / 账号密码登录 / 登录按钮 / 提交登录", roles: ["guest"], route: "/pages/auth/login", fields: ["登录按钮（按钮）"], actions: ["提交登录"], states: ["验证通过跳转主页", "存储Token，跳转主页"], evidence: ["docx:table-row-020", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-020"], status: "complete-local" },
  { sourceRow: 21, requirement: "账号系统 / 登录 / 第三方登录 / Google登录 / Google账号登录", roles: ["guest"], route: "/pages/auth/login", fields: ["Google登录（第三方按钮）"], actions: ["Google账号登录"], states: ["仅海外版显示", "调用Google OAuth2.0"], evidence: ["docx:table-row-021", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-021"], status: "simulated-local" },
  { sourceRow: 22, requirement: "账号系统 / 登录 / 第三方登录 / 微信登录 / 微信账号登录", roles: ["guest"], route: "/pages/auth/login", fields: ["微信登录（第三方按钮）"], actions: ["微信账号登录"], states: ["仅国内版显示", "调用微信SDK"], evidence: ["docx:table-row-022", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-022"], status: "simulated-local" },
  { sourceRow: 23, requirement: "账号系统 / 登录 / Apple登录 / Apple授权 / Apple账号一键登录（国内+海外）", roles: ["guest"], route: "/pages/auth/login", fields: ["Apple授权（第三方按钮）"], actions: ["Apple账号一键登录（国内+海外）"], states: ["iOS端必选，需配置Apple Sign-In", "调用Apple OAuth2.0"], evidence: ["docx:table-row-023", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-023"], status: "simulated-local" },
  { sourceRow: 24, requirement: "账号系统 / 登录 / 安全机制 / 账号锁定 / 密码错误5次锁定30分钟", roles: ["guest"], route: "/pages/auth/login", fields: ["账号锁定（系统逻辑）"], actions: ["密码错误5次锁定30分钟"], states: ["显示剩余解锁时间", "缓存记录错误次数，达5次设锁定标记"], evidence: ["docx:table-row-024", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-024"], status: "complete-local" },
  { sourceRow: 25, requirement: "账号系统 / 忘记密码 / 身份验证 / 邮箱/手机号 / 输入注册账号", roles: ["guest"], route: "/pages/auth/password?mode=forgot", fields: ["邮箱/手机号（文本输入框）"], actions: ["输入注册账号"], states: ["必填", "验证账号存在"], evidence: ["docx:table-row-025", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-025"], status: "complete-local" },
  { sourceRow: 26, requirement: "账号系统 / 忘记密码 / 身份验证 / 验证码 / 输入验证码", roles: ["guest"], route: "/pages/auth/password?mode=forgot", fields: ["验证码（输入框+按钮）"], actions: ["输入验证码"], states: ["6位，60秒倒计时", "发送验证码，缓存5分钟"], evidence: ["docx:table-row-026", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-026"], status: "simulated-local" },
  { sourceRow: 27, requirement: "账号系统 / 忘记密码 / 重置密码 / 新密码 / 输入新密码", roles: ["guest"], route: "/pages/auth/password?mode=forgot", fields: ["新密码（密码输入框）"], actions: ["输入新密码"], states: ["8-20位，含字母和数字", "校验强度"], evidence: ["docx:table-row-027", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-027"], status: "complete-local" },
  { sourceRow: 28, requirement: "账号系统 / 忘记密码 / 重置密码 / 确认密码 / 再次输入新密码", roles: ["guest"], route: "/pages/auth/password?mode=forgot", fields: ["确认密码（密码输入框）"], actions: ["再次输入新密码"], states: ["需与新密码一致", "一致后调用重置接口，清除缓存验证码"], evidence: ["docx:table-row-028", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-028"], status: "complete-local" },
  { sourceRow: 29, requirement: "账号系统 / 个人资料 / 资料展示 / 头像 / 显示用户头像", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/profile/detail?mode=view", fields: ["头像（图片）"], actions: ["显示用户头像"], states: ["点击可修改", "从用户表读取头像URL"], evidence: ["docx:table-row-029", "src/services/profile.ts", "tests/v32-requirements.test.ts#row-029"], status: "complete-local" },
  { sourceRow: 30, requirement: "账号系统 / 个人资料 / 资料展示 / 昵称 / 显示用户昵称", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/profile/detail?mode=view", fields: ["昵称（文本）"], actions: ["显示用户昵称"], states: ["点击可修改", "从用户表读取"], evidence: ["docx:table-row-030", "src/services/profile.ts", "tests/v32-requirements.test.ts#row-030"], status: "complete-local" },
  { sourceRow: 31, requirement: "账号系统 / 个人资料 / 资料展示 / 账号 / 显示邮箱/手机号", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/profile/detail?mode=view", fields: ["账号（文本）"], actions: ["显示邮箱/手机号"], states: ["脱敏显示", "中间部分星号替换"], evidence: ["docx:table-row-031", "src/services/profile.ts", "tests/v32-requirements.test.ts#row-031"], status: "complete-local" },
  { sourceRow: 32, requirement: "账号系统 / 个人资料 / 资料编辑 / 修改头像 / 上传新头像", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/profile/detail?mode=edit", fields: ["修改头像（图片上传）"], actions: ["上传新头像"], states: ["jpg/png，≤5MB", "调用上传接口，更新用户表"], evidence: ["docx:table-row-032", "src/services/profile.ts", "tests/v32-requirements.test.ts#row-032"], status: "complete-local" },
  { sourceRow: 33, requirement: "账号系统 / 个人资料 / 资料编辑 / 修改昵称 / 修改昵称", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/profile/detail?mode=edit", fields: ["修改昵称（文本输入框）"], actions: ["修改昵称"], states: ["2-20字符", "调用更新接口"], evidence: ["docx:table-row-033", "src/services/profile.ts", "tests/v32-requirements.test.ts#row-033"], status: "complete-local" },
  { sourceRow: 34, requirement: "账号系统 / 个人资料 / 资料编辑 / 修改密码 / 修改登录密码", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/auth/password?mode=reset", fields: ["修改密码（密码输入框）"], actions: ["修改登录密码"], states: ["需验证旧密码", "验证旧密码后更新"], evidence: ["docx:table-row-034", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-034"], status: "complete-local" },
  { sourceRow: 35, requirement: "账号系统 / 退出登录 / 退出确认 / 确认弹窗 / 确认是否退出", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/profile/settings", fields: ["确认弹窗（弹窗）"], actions: ["确认是否退出"], states: ["点击确认清除登录状态", "清除Token，调用登出接口，跳转登录页"], evidence: ["docx:table-row-035", "src/services/auth.ts", "tests/v32-requirements.test.ts#row-035"], status: "complete-local" },
  { sourceRow: 36, requirement: "主页 / Banner / Banner展示 / Banner图片 / 展示3张Banner", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=home", fields: ["Banner图片（图片轮播）"], actions: ["展示3张Banner"], states: ["支持自动轮播，点击跳转", "后台配置内容，APP轮播展示"], evidence: ["docx:table-row-036", "src/pages/shell/index.vue", "tests/v32-requirements.test.ts#row-036"], status: "complete-local" },
  { sourceRow: 37, requirement: "主页 / 设备列表 / 设备缩略图 / 设备图片 / 展示已绑定的多类型设备缩略图", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=home", fields: ["设备图片（卡片列表）"], actions: ["展示已绑定的多类型设备缩略图"], states: ["支持横向滑动，类似米家多设备", "查询用户绑定设备表，按设备类型展示图标"], evidence: ["docx:table-row-037", "src/pages/shell/index.vue", "tests/v32-requirements.test.ts#row-037"], status: "complete-local" },
  { sourceRow: 38, requirement: "主页 / 设备列表 / 设备缩略图 / 设备名称 / 显示设备名称及型号", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=home", fields: ["设备名称（文本）"], actions: ["显示设备名称及型号"], states: ["从设备表读取"], evidence: ["docx:table-row-038", "src/pages/shell/index.vue", "tests/v32-requirements.test.ts#row-038"], status: "complete-local" },
  { sourceRow: 39, requirement: "主页 / 设备列表 / 设备缩略图 / 设备类型标签 / 显示设备类型", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=home", fields: ["设备类型标签（标签）"], actions: ["显示设备类型"], states: ["顶流机/制冰机/海水淡化器/电池等", "从设备类型表读取"], evidence: ["docx:table-row-039", "src/pages/shell/index.vue", "tests/v32-requirements.test.ts#row-039"], status: "complete-local" },
  { sourceRow: 40, requirement: "主页 / 设备列表 / 设备缩略图 / 连接状态 / 显示在线/离线", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=home", fields: ["连接状态（状态标签）"], actions: ["显示在线/离线"], states: ["在线绿色，离线灰色", "蓝牙/网络检测连接状态"], evidence: ["docx:table-row-040", "src/pages/shell/index.vue", "tests/v32-requirements.test.ts#row-040"], status: "simulated-local" },
  { sourceRow: 41, requirement: "主页 / 设备列表 / 添加设备入口 / 添加按钮 / 进入设备添加流程", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=home", fields: ["添加按钮（图标按钮）"], actions: ["进入设备添加流程"], states: ["跳转设备添加模块"], evidence: ["docx:table-row-041", "src/pages/shell/index.vue", "tests/v32-requirements.test.ts#row-041"], status: "complete-local" },
  { sourceRow: 42, requirement: "主页 / APP设置 / 通知设置 / 消息推送开关 / 开启/关闭消息推送", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/profile/settings?section=notifications", fields: ["消息推送开关（开关）"], actions: ["开启/关闭消息推送"], states: ["调用系统通知权限API"], evidence: ["docx:table-row-042", "src/pages/manage/form.vue", "tests/v32-requirements.test.ts#row-042"], status: "simulated-local" },
  { sourceRow: 43, requirement: "主页 / APP设置 / 语言设置 / 语言选择 / 选择APP显示语言（客户追加 13 种语言）", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/profile/settings?section=language", fields: ["中文、英文、韩语、日语、土耳其语、阿拉伯语、葡萄牙语、西班牙语、法语、德语、意大利语、荷兰语、俄语"], actions: ["选择APP显示语言", "应用并重新启动"], states: ["13 种语言可选", "选择结果本地持久化", "阿拉伯语 RTL", "非中文完整英文回退"], evidence: ["docx:table-row-043", "customer-change:2026-08-25", "src/config/locales.ts", "src/pages/profile/settings.vue", "tests/locales.test.ts", "tests/e2e/app.spec.ts#language-settings", "tests/v32-requirements.test.ts#row-043"], status: "complete-local" },
  { sourceRow: 44, requirement: "主页 / 客服与帮助 / 留言提交 / 问题描述 / 输入问题描述", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=message", fields: ["问题描述（文本域）"], actions: ["输入问题描述"], states: ["必填，≤500字", "保存到留言表，关联用户ID"], evidence: ["docx:table-row-044", "src/pages/manage/form.vue", "tests/v32-requirements.test.ts#row-044"], status: "complete-local" },
  { sourceRow: 45, requirement: "主页 / 客服与帮助 / 留言提交 / 联系电话 / 输入联系电话", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=message", fields: ["联系电话（文本输入框）"], actions: ["输入联系电话"], states: ["电话和邮件至少填一个", "自动带出账号手机号，可修改"], evidence: ["docx:table-row-045", "src/pages/manage/form.vue", "tests/v32-requirements.test.ts#row-045"], status: "complete-local" },
  { sourceRow: 46, requirement: "主页 / 客服与帮助 / 留言提交 / 联系邮件 / 输入联系邮箱", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=message", fields: ["联系邮件（文本输入框）"], actions: ["输入联系邮箱"], states: ["电话和邮件至少填一个", "自动带出账号邮箱，可修改"], evidence: ["docx:table-row-046", "src/pages/manage/form.vue", "tests/v32-requirements.test.ts#row-046"], status: "complete-local" },
  { sourceRow: 47, requirement: "主页 / 客服与帮助 / 留言提交 / 提交按钮 / 提交留言", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=message", fields: ["提交按钮（按钮）"], actions: ["提交留言"], states: ["至少填一种联系方式", "后台自动转发给代理商或官方"], evidence: ["docx:table-row-047", "src/pages/manage/form.vue", "tests/v32-requirements.test.ts#row-047"], status: "complete-local" },
  { sourceRow: 48, requirement: "设备添加\n与解密 / 搜索连接设备 / 蓝牙搜索 / 周边设备列表 / 扫描周边蓝牙设备", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=2", fields: ["周边设备列表（列表）"], actions: ["扫描周边蓝牙设备"], states: ["需开启蓝牙权限", "调用蓝牙API扫描，展示设备名和信号强度"], evidence: ["docx:table-row-048", "src/services/device.ts", "tests/v32-requirements.test.ts#row-048"], status: "simulated-local" },
  { sourceRow: 49, requirement: "设备添加\n与解密 / 搜索连接设备 / 蓝牙搜索 / 连接按钮 / 连接选中设备", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=2", fields: ["连接按钮（按钮）"], actions: ["连接选中设备"], states: ["建立蓝牙连接，成功后进入绑定流程"], evidence: ["docx:table-row-049", "src/services/device.ts", "tests/v32-requirements.test.ts#row-049"], status: "simulated-local" },
  { sourceRow: 50, requirement: "设备添加\n与解密 / 绑定设备 / 扫码绑定 / 扫码按钮 / 扫描设备二维码获取序列号", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=2", fields: ["扫码按钮（扫码）"], actions: ["扫描设备二维码获取序列号"], states: ["调用摄像头扫描，解析序列号"], evidence: ["docx:table-row-050", "src/services/device.ts", "tests/v32-requirements.test.ts#row-050"], status: "complete-local" },
  { sourceRow: 51, requirement: "设备添加\n与解密 / 绑定设备 / 手动绑定 / 序列号输入 / 手动输入设备序列号", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=2", fields: ["序列号输入（文本输入框）"], actions: ["手动输入设备序列号"], states: ["必填，格式校验", "输入后调用绑定接口"], evidence: ["docx:table-row-051", "src/services/device.ts", "tests/v32-requirements.test.ts#row-051"], status: "complete-local" },
  { sourceRow: 52, requirement: "设备添加\n与解密 / 绑定设备 / 手动绑定 / 完成绑定 / 提交绑定请求", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=2", fields: ["完成绑定（按钮）"], actions: ["提交绑定请求"], states: ["关联用户ID与设备序列号"], evidence: ["docx:table-row-052", "src/services/device.ts", "tests/v32-requirements.test.ts#row-052"], status: "complete-local" },
  { sourceRow: 53, requirement: "设备添加\n与解密 / 设备校验\n（防串货核心） / 地区校对 / 手机定位 / 获取手机GPS定位", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=4", fields: ["手机定位（系统逻辑）"], actions: ["获取手机GPS定位"], states: ["需开启位置权限，国内用高德/百度，海外用谷歌", "调用对应地图SDK定位API"], evidence: ["docx:table-row-053", "src/services/device.ts", "tests/v32-requirements.test.ts#row-053"], status: "partial" },
  { sourceRow: 54, requirement: "设备添加\n与解密 / 设备校验\n（防串货核心） / 地区校对 / 地区比对 / 将手机定位与设备销售区域（省市区）比对", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=4", fields: ["地区比对（系统逻辑）"], actions: ["将手机定位与设备销售区域（省市区）比对"], states: ["海外精确到国家，后台提前录入销售地区", "查询后台设备销售地区配置，匹配则自动解密激活"], evidence: ["docx:table-row-054", "src/services/device.ts", "tests/v32-requirements.test.ts#row-054"], status: "partial" },
  { sourceRow: 55, requirement: "地图集成 / 国内地图 / 地区校对 / 高德/百度地图 / 国内版设备使用高德或百度地图展示航点标记、地区校验位置", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=map", fields: ["高德/百度地图（地图组件）"], actions: ["国内版设备使用高德或百度地图展示航点标记、地区校验位置"], states: ["国内版默认使用，需申请地图SDK Key", "集成高德/百度地图SDK，展示地图界面"], evidence: ["docx:table-row-055", "src/services/device.ts", "tests/v32-requirements.test.ts#row-055"], status: "partial" },
  { sourceRow: 56, requirement: "地图集成 / 海外地图 / 地区校对 / 谷歌地图 / 海外版设备使用谷歌地图展示航点标记、地区校验位置", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=map", fields: ["谷歌地图（地图组件）"], actions: ["海外版设备使用谷歌地图展示航点标记、地区校验位置"], states: ["海外版默认使用，需Google服务支持", "集成Google Maps SDK，展示地图界面"], evidence: ["docx:table-row-056", "src/services/device.ts", "tests/v32-requirements.test.ts#row-056"], status: "partial" },
  { sourceRow: 57, requirement: "地图集成 / 定位服务 / 地区校对 / GPS定位 / 获取手机设备GPS定位信息", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=map", fields: ["GPS定位（系统逻辑）"], actions: ["获取手机设备GPS定位信息"], states: ["需开启位置权限", "调用对应地图SDK定位API，用于地区校对和航点标记"], evidence: ["docx:table-row-057", "src/services/device.ts", "tests/v32-requirements.test.ts#row-057"], status: "partial" },
  { sourceRow: 58, requirement: "地图集成 / 海图规划 / 地区校对 / 海图航线 / 在海图上规划航行路线，标记航点之间的航线", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=route", fields: ["海图航线（地图组件）"], actions: ["在海图上规划航行路线，标记航点之间的航线"], states: ["仅已绑定设备的用户可见此模块", "在地图上绘制航线，支持拖拽调整"], evidence: ["docx:table-row-058", "src/services/device.ts", "tests/v32-requirements.test.ts#row-058"], status: "complete-local" },
  { sourceRow: 59, requirement: "Excel 原始需求表空白行", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=route", fields: [], actions: [], states: [], evidence: ["xlsx:APP端功能列表:row-059", "src/services/device.ts", "tests/v32-requirements.test.ts#row-059"], status: "source-blank" },
  { sourceRow: 60, requirement: "Excel 原始需求表空白行", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=route", fields: [], actions: [], states: [], evidence: ["xlsx:APP端功能列表:row-060", "src/services/device.ts", "tests/v32-requirements.test.ts#row-060"], status: "source-blank" },
  { sourceRow: 61, requirement: "地图集成 / 海图规划 / 地区校对 / 地区匹配-自动解密 / 地区校对通过后自动解密设备", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=4", fields: ["地区匹配-自动解密（系统逻辑）"], actions: ["地区校对通过后自动解密设备"], states: ["无需用户操作", "调用解密接口，更新设备激活状态"], evidence: ["docx:table-row-061", "src/services/device.ts", "tests/v32-requirements.test.ts#row-061"], status: "complete-local" },
  { sourceRow: 62, requirement: "地图集成 / 海图规划 / 地区校对 / 地区不匹配提示 / 提示地区不匹配，引导联系代理商", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=4", fields: ["地区不匹配提示（弹窗）"], actions: ["提示地区不匹配，引导联系代理商"], states: ["显示代理商或官方客服联系方式", "展示提示弹窗，提供联系方式"], evidence: ["docx:table-row-062", "src/services/device.ts", "tests/v32-requirements.test.ts#row-062"], status: "complete-local" },
  { sourceRow: 63, requirement: "地图集成 / 海图规划 / 二手机处理 / 已绑定提示 / 提示设备已被绑定，需先解绑", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=4", fields: ["已绑定提示（弹窗）"], actions: ["提示设备已被绑定，需先解绑"], states: ["查询绑定状态，已绑定则提示联系原代理解绑"], evidence: ["docx:table-row-063", "src/services/device.ts", "tests/v32-requirements.test.ts#row-063"], status: "complete-local" },
  { sourceRow: 64, requirement: "地图集成 / 海图规划 / 二手机处理 / 已解绑可绑定 / 设备解绑后可被新用户绑定", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=4", fields: ["已解绑可绑定（系统逻辑）"], actions: ["设备解绑后可被新用户绑定"], states: ["设备状态为已解绑时允许新用户绑定"], evidence: ["docx:table-row-064", "src/services/device.ts", "tests/v32-requirements.test.ts#row-064"], status: "complete-local" },
  { sourceRow: 65, requirement: "地图集成 / 海图规划 / 未创建项目提示 / 无法解锁提示 / 序列号未在系统创建项目则无法解锁", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/add?step=4", fields: ["无法解锁提示（弹窗）"], actions: ["序列号未在系统创建项目则无法解锁"], states: ["后台需提前录入设备及销售地区", "查询项目表，序列号不存在则提示无法解锁"], evidence: ["docx:table-row-065", "src/services/device.ts", "tests/v32-requirements.test.ts#row-065"], status: "partial" },
  { sourceRow: 66, requirement: "设备主页 / 设备连接 / 连接状态 / 蓝牙状态 / 显示蓝牙连接状态", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/detail?id=dev-01", fields: ["蓝牙状态（状态指示）"], actions: ["显示蓝牙连接状态"], states: ["已连接/未连接", "实时检测蓝牙状态"], evidence: ["docx:table-row-066", "src/services/device.ts", "tests/v32-requirements.test.ts#row-066"], status: "simulated-local" },
  { sourceRow: 67, requirement: "设备主页 / 设备连接 / 连接状态 / 遥控器状态 / 显示遥控器连接状态", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/detail?id=dev-01", fields: ["遥控器状态（状态指示）"], actions: ["显示遥控器连接状态"], states: ["支持同时连接遥控器与APP", "同时显示两端连接状态"], evidence: ["docx:table-row-067", "src/services/device.ts", "tests/v32-requirements.test.ts#row-067"], status: "simulated-local" },
  { sourceRow: 68, requirement: "设备主页 / 设备信息 / 信息展示 / 激活日期 / 显示设备激活日期", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/detail?id=dev-01", fields: ["激活日期（日期文本）"], actions: ["显示设备激活日期"], states: ["从设备表读取激活时间"], evidence: ["docx:table-row-068", "src/services/device.ts", "tests/v32-requirements.test.ts#row-068"], status: "complete-local" },
  { sourceRow: 69, requirement: "设备主页 / 设备信息 / 信息展示 / 使用时长 / 显示累计使用时长", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/detail?id=dev-01", fields: ["使用时长（时长文本）"], actions: ["显示累计使用时长"], states: ["更换主板后同步主板数据保存", "累加统计，换主板时同步历史数据"], evidence: ["docx:table-row-069", "src/services/device.ts", "tests/v32-requirements.test.ts#row-069"], status: "complete-local" },
  { sourceRow: 70, requirement: "设备主页 / 设备信息 / 信息展示 / 固件版本 / 显示当前固件版本号", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/detail?id=dev-01", fields: ["固件版本（文本）"], actions: ["显示当前固件版本号"], states: ["从设备表读取版本字段"], evidence: ["docx:table-row-070", "src/services/device.ts", "tests/v32-requirements.test.ts#row-070"], status: "complete-local" },
  { sourceRow: 71, requirement: "设备主页 / 设备信息 / 信息展示 / 序列号 / 显示设备序列号", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/detail?id=dev-01", fields: ["序列号（文本）"], actions: ["显示设备序列号"], states: ["从设备表读取"], evidence: ["docx:table-row-071", "src/services/device.ts", "tests/v32-requirements.test.ts#row-071"], status: "complete-local" },
  { sourceRow: 72, requirement: "设备主页 / 设备信息 / 信息展示 / 设备类型 / 显示设备类型", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/device/detail?id=dev-01", fields: ["设备类型（文本）"], actions: ["显示设备类型"], states: ["顶流机/制冰机/海水淡化器/电池等", "从设备类型表读取"], evidence: ["docx:table-row-072", "src/services/device.ts", "tests/v32-requirements.test.ts#row-072"], status: "complete-local" },
  { sourceRow: 73, requirement: "设备主页 / 控制面板 / 参数显示 / 遥控器参数 / 实时显示遥控器参数", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=control", fields: ["遥控器参数（参数展示）"], actions: ["实时显示遥控器参数"], states: ["同遥控器显示内容，不同设备类型参数不同", "蓝牙实时读取参数，H5页面动态渲染，便于后续迭代"], evidence: ["docx:table-row-073", "src/services/device.ts", "tests/v32-requirements.test.ts#row-073"], status: "partial" },
  { sourceRow: 74, requirement: "设备主页 / 控制面板 / 操控功能 / 模式切换 / 切换设备工作模式", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=control", fields: ["模式切换（按钮）"], actions: ["切换设备工作模式"], states: ["同遥控器，不同设备类型功能不同", "发送蓝牙指令切换模式，H5实现便于扩展"], evidence: ["docx:table-row-074", "src/services/device.ts", "tests/v32-requirements.test.ts#row-074"], status: "simulated-local" },
  { sourceRow: 75, requirement: "设备主页 / 控制面板 / 操控功能 / 升降控制 / 控制设备升降", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=control", fields: ["升降控制（按钮）"], actions: ["控制设备升降"], states: ["同遥控器（顶流机适用）", "发送蓝牙升降指令"], evidence: ["docx:table-row-075", "src/services/device.ts", "tests/v32-requirements.test.ts#row-075"], status: "simulated-local" },
  { sourceRow: 76, requirement: "设备主页 / 控制面板 / 操控功能 / 方向控制 / 上下左右方向控制", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=control", fields: ["方向控制（方向按钮）"], actions: ["上下左右方向控制"], states: ["同遥控器", "发送蓝牙方向指令"], evidence: ["docx:table-row-076", "src/services/device.ts", "tests/v32-requirements.test.ts#row-076"], status: "simulated-local" },
  { sourceRow: 77, requirement: "设备主页 / 控制面板 / 操控功能 / 螺旋桨开关 / 控制螺旋桨启停", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=control", fields: ["螺旋桨开关（开关按钮）"], actions: ["控制螺旋桨启停"], states: ["同遥控器", "发送蓝牙螺旋桨指令"], evidence: ["docx:table-row-077", "src/services/device.ts", "tests/v32-requirements.test.ts#row-077"], status: "simulated-local" },
  { sourceRow: 78, requirement: "设备主页 / 设备设置 / 参数设置 / 设置项列表 / 配置设备参数", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=settings", fields: ["设置项列表（菜单列表）"], actions: ["配置设备参数"], states: ["无遥控器后台设置功能，其他同遥控器", "展示可配置参数，发送蓝牙指令修改，H5实现"], evidence: ["docx:table-row-078", "src/services/device.ts", "tests/v32-requirements.test.ts#row-078"], status: "partial" },
  { sourceRow: 79, requirement: "设备主页 / 航点标记 / 标记操作 / 保存当前位置 / 保存设备当前GPS坐标", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=map", fields: ["保存当前位置（按钮）"], actions: ["保存设备当前GPS坐标"], states: ["默认保存本地需手动上传", "调用对应地图SDK获取坐标，存本地数据库"], evidence: ["docx:table-row-079", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-079"], status: "partial" },
  { sourceRow: 80, requirement: "设备主页 / 航点标记 / 标记操作 / 位置名称 / 为航点命名", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=map", fields: ["位置名称（文本输入框）"], actions: ["为航点命名"], states: ["支持编辑", "与坐标一起保存"], evidence: ["docx:table-row-080", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-080"], status: "complete-local" },
  { sourceRow: 81, requirement: "设备主页 / 航点标记 / 标记操作 / 地图展示 / 在地图上显示当前位置", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=map", fields: ["地图展示（地图组件）"], actions: ["在地图上显示当前位置"], states: ["国内高德/百度，海外谷歌", "调用对应地图SDK展示地图和标记点"], evidence: ["docx:table-row-081", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-081"], status: "partial" },
  { sourceRow: 82, requirement: "设备主页 / 航点标记 / 标记操作 / 上传到后台 / 手动上传航点到服务器", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=map", fields: ["上传到后台（按钮）"], actions: ["手动上传航点到服务器"], states: ["需用户手动触发，数据随用户账号保存", "调用上传接口，同步到服务器"], evidence: ["docx:table-row-082", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-082"], status: "simulated-local" },
  { sourceRow: 83, requirement: "设备主页 / 航点标记 / 航点列表 / 航点名称 / 显示已标记航点名称", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=waypoints", fields: ["航点名称（文本）"], actions: ["显示已标记航点名称"], states: ["在用户资料和设备入口均有入口", "从本地数据库读取"], evidence: ["docx:table-row-083", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-083"], status: "complete-local" },
  { sourceRow: 84, requirement: "设备主页 / 航点标记 / 航点列表 / 坐标信息 / 显示经纬度坐标", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=waypoints", fields: ["坐标信息（文本）"], actions: ["显示经纬度坐标"], states: ["格式化显示GPS坐标"], evidence: ["docx:table-row-084", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-084"], status: "complete-local" },
  { sourceRow: 85, requirement: "设备主页 / 航点标记 / 航点列表 / 删除航点 / 删除选中航点", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=waypoints", fields: ["删除航点（按钮）"], actions: ["删除选中航点"], states: ["需二次确认", "从本地数据库删除"], evidence: ["docx:table-row-085", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-085"], status: "complete-local" },
  { sourceRow: 86, requirement: "设备主页 / 航点回放 / 回放操作 / 航点列表 / 显示已标记航点", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=waypoints", fields: ["航点列表（列表）"], actions: ["显示已标记航点"], states: ["读取本地或服务器航点数据"], evidence: ["docx:table-row-086", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-086"], status: "complete-local" },
  { sourceRow: 87, requirement: "设备主页 / 航点回放 / 回放操作 / 触发导航 / 设备按选定航点推进", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=playback", fields: ["触发导航（按钮）"], actions: ["设备按选定航点推进"], states: ["发送蓝牙指令，设备按坐标推进"], evidence: ["docx:table-row-087", "src/services/routes.ts", "tests/v32-requirements.test.ts#row-087"], status: "partial" },
  { sourceRow: 88, requirement: "设备主页 / 故障报修 / 报修表单 / 故障分类 / 选择故障类型", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=repair", fields: ["故障分类（下拉选择）"], actions: ["选择故障类型"], states: ["水下电机/提升/转向/接线盒/其他", "保存到报修表"], evidence: ["docx:table-row-088", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-088"], status: "complete-local" },
  { sourceRow: 89, requirement: "设备主页 / 故障报修 / 报修表单 / 故障描述 / 描述故障情况", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=repair", fields: ["故障描述（文本域）"], actions: ["描述故障情况"], states: ["选填，≤500字", "保存到报修表"], evidence: ["docx:table-row-089", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-089"], status: "complete-local" },
  { sourceRow: 90, requirement: "设备主页 / 故障报修 / 报修表单 / 联系电话 / 联系电话", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=repair", fields: ["联系电话（文本输入框）"], actions: ["联系电话"], states: ["至少填一种，可修改", "自动带出账号联系方式"], evidence: ["docx:table-row-090", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-090"], status: "complete-local" },
  { sourceRow: 91, requirement: "设备主页 / 故障报修 / 报修表单 / 联系邮件 / 联系邮箱", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=repair", fields: ["联系邮件（文本输入框）"], actions: ["联系邮箱"], states: ["至少填一种，可修改", "自动带出账号邮箱"], evidence: ["docx:table-row-091", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-091"], status: "complete-local" },
  { sourceRow: 92, requirement: "设备主页 / 故障报修 / 报修表单 / 提交按钮 / 提交报修申请", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=repair", fields: ["提交按钮（按钮）"], actions: ["提交报修申请"], states: ["后台推送给地区总代理或已绑定代理商"], evidence: ["docx:table-row-092", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-092"], status: "simulated-local" },
  { sourceRow: 93, requirement: "OTA / 版本检测 / 自动检测 / 版本比对 / 联机后自动检测主板版本", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=ota", fields: ["版本比对（系统逻辑）"], actions: ["联机后自动检测主板版本"], states: ["OTA入口在设置中", "连接设备后读取版本，与服务器最新版本比对，需与硬件联调适配"], evidence: ["docx:table-row-093", "src/services/firmware.ts", "tests/v32-requirements.test.ts#row-093"], status: "partial" },
  { sourceRow: 94, requirement: "OTA / 版本检测 / 自动检测 / 更新提示 / 有新版本时弹窗提示", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=ota", fields: ["更新提示（弹窗）"], actions: ["有新版本时弹窗提示"], states: ["用户可选立即更新或稍后", "检测到新版本后弹出提示"], evidence: ["docx:table-row-094", "src/services/firmware.ts", "tests/v32-requirements.test.ts#row-094"], status: "partial" },
  { sourceRow: 95, requirement: "OTA / OTA升级 / 固件更新 / 下载固件 / 从服务器下载最新固件", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=ota", fields: ["下载固件（进度条）"], actions: ["从服务器下载最新固件"], states: ["显示下载进度", "调用下载接口，显示百分比"], evidence: ["docx:table-row-095", "src/services/firmware.ts", "tests/v32-requirements.test.ts#row-095"], status: "simulated-local" },
  { sourceRow: 96, requirement: "OTA / OTA升级 / 固件更新 / 蓝牙传输 / 通过蓝牙传输固件到主板", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=ota", fields: ["蓝牙传输（进度条）"], actions: ["通过蓝牙传输固件到主板"], states: ["显示传输进度，需与硬件联调", "分包传输，显示进度，驱动器及开关板暂不支持"], evidence: ["docx:table-row-096", "src/services/firmware.ts", "tests/v32-requirements.test.ts#row-096"], status: "simulated-local" },
  { sourceRow: 97, requirement: "OTA / OTA升级 / 固件更新 / 更新结果 / 显示更新成功或失败", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=ota", fields: ["更新结果（提示）"], actions: ["显示更新成功或失败"], states: ["失败时提供重试选项", "更新完成后提示结果"], evidence: ["docx:table-row-097", "src/services/firmware.ts", "tests/v32-requirements.test.ts#row-097"], status: "simulated-local" },
  { sourceRow: 98, requirement: "经销商板块 / 权限入口 / 权限控制 / 经销商模块入口 / 仅有经销商权限的用户显示", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=workbench", fields: ["经销商模块入口（模块入口）"], actions: ["仅有经销商权限的用户显示"], states: ["后台分配权限", "登录后检查角色，有权限才展示"], evidence: ["docx:table-row-098", "src/services/authorization.ts", "tests/v32-requirements.test.ts#row-098"], status: "complete-local" },
  { sourceRow: 99, requirement: "经销商板块 / 权限入口 / 权限控制 / 二级经销商 / 支持设立二级经销商", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=workbench", fields: ["二级经销商（系统逻辑）"], actions: ["支持设立二级经销商"], states: ["权限受限于上级", "一级经销商可创建二级账号"], evidence: ["docx:table-row-099", "src/services/authorization.ts", "tests/v32-requirements.test.ts#row-099"], status: "complete-local" },
  { sourceRow: 100, requirement: "经销商板块 / 权限入口 / 权限控制 / 设备及配件等商品采购 / 一级代理商向公司采购，二级代理向总代采购", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=purchases&state=catalog", fields: ["设备及配件采购（模块入口）"], actions: ["浏览采购目录并创建采购单"], states: ["一级代理商向公司采购", "二级代理商向所属总代采购"], evidence: ["xlsx:APP端功能列表:row-100", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-100"], status: "complete-local" },
  { sourceRow: 101, requirement: "经销商板块 / 权限入口 / 权限控制 / 员工账号 / 支持设立员工账号", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/shell/index?tab=workbench", fields: ["员工账号（系统逻辑）"], actions: ["支持设立员工账号"], states: ["有限操作权限", "经销商创建员工账号并分配权限"], evidence: ["docx:table-row-101", "src/services/authorization.ts", "tests/v32-requirements.test.ts#row-101"], status: "complete-local" },
  { sourceRow: 102, requirement: "经销商板块 / 项目管理 / 项目创建 / 船名 / 输入船只名称", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["船名（文本输入框）"], actions: ["输入船只名称"], states: ["必填", "保存到项目表"], evidence: ["docx:table-row-102", "src/services/project.ts", "tests/v32-requirements.test.ts#row-102"], status: "complete-local" },
  { sourceRow: 103, requirement: "经销商板块 / 项目管理 / 项目创建 / 设备SN号 / 输入设备序列号", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["设备SN号（文本输入框）"], actions: ["输入设备序列号"], states: ["必填，关联设备", "验证SN存在，关联项目与设备"], evidence: ["docx:table-row-103", "src/services/project.ts", "tests/v32-requirements.test.ts#row-103"], status: "complete-local" },
  { sourceRow: 104, requirement: "经销商板块 / 项目管理 / 项目创建 / 船东姓名 / 输入船东姓名", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["船东姓名（文本输入框）"], actions: ["输入船东姓名"], states: ["必填", "保存到项目表"], evidence: ["docx:table-row-104", "src/services/project.ts", "tests/v32-requirements.test.ts#row-104"], status: "complete-local" },
  { sourceRow: 105, requirement: "经销商板块 / 项目管理 / 项目创建 / 设备型号 / 选择设备型号", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["设备型号（下拉选择）"], actions: ["选择设备型号"], states: ["必填，支持多种设备类型", "从设备型号表读取"], evidence: ["docx:table-row-105", "src/services/project.ts", "tests/v32-requirements.test.ts#row-105"], status: "complete-local" },
  { sourceRow: 106, requirement: "经销商板块 / 项目管理 / 项目创建 / 杆长 / 输入杆长规格", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["杆长（文本输入框）"], actions: ["输入杆长规格"], states: ["必填", "保存到项目表"], evidence: ["docx:table-row-106", "src/services/project.ts", "tests/v32-requirements.test.ts#row-106"], status: "complete-local" },
  { sourceRow: 107, requirement: "经销商板块 / 项目管理 / 项目创建 / 使用地区 / 输入使用地区", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["使用地区（文本输入框）"], actions: ["输入使用地区"], states: ["必填", "保存到项目表"], evidence: ["docx:table-row-107", "src/services/project.ts", "tests/v32-requirements.test.ts#row-107"], status: "complete-local" },
  { sourceRow: 108, requirement: "经销商板块 / 项目管理 / 项目创建 / 联系电话 / 客户联系电话", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["联系电话（文本输入框）"], actions: ["客户联系电话"], states: ["必填", "保存到项目表"], evidence: ["docx:table-row-108", "src/services/project.ts", "tests/v32-requirements.test.ts#row-108"], status: "complete-local" },
  { sourceRow: 109, requirement: "经销商板块 / 项目管理 / 项目创建 / 联系邮箱 / 客户联系邮箱", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["联系邮箱（文本输入框）"], actions: ["客户联系邮箱"], states: ["选填", "保存到项目表"], evidence: ["docx:table-row-109", "src/services/project.ts", "tests/v32-requirements.test.ts#row-109"], status: "complete-local" },
  { sourceRow: 110, requirement: "经销商板块 / 项目管理 / 项目创建 / 质保期 / 设置质保到期日期", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["质保期（日期选择器）"], actions: ["设置质保到期日期"], states: ["保存质保期", "到期前推送提醒"], evidence: ["xlsx:APP端功能列表:row-110", "src/services/project.ts", "tests/v32-requirements.test.ts#row-110"], status: "complete-local" },
  { sourceRow: 111, requirement: "经销商板块 / 项目管理 / 其他说明 / 安装项目与售后项目业务规则", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=projects", fields: ["项目类型", "原物料", "新物料", "故障原因", "收费情况"], actions: ["基于安装项目创建售后项目"], states: ["安装项目", "售后项目", "新物料有效且保留原物料记录"], evidence: ["xlsx:APP端功能列表:row-111", "src/services/project.ts", "tests/v32-requirements.test.ts#row-111"], status: "complete-local" },
  { sourceRow: 112, requirement: "经销商板块 / 项目管理 / 已激活未建项目设备 / 推送补建并支持项目设备双向查询", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=projects&state=result", fields: ["待补建项目提醒", "设备", "项目"], actions: ["为已激活设备补建项目", "按产品查项目", "按项目查设备"], states: ["已绑定激活但未添加项目", "推送至所属代理商"], evidence: ["xlsx:APP端功能列表:row-112", "src/services/project.ts", "tests/v32-requirements.test.ts#row-112"], status: "complete-local" },
  { sourceRow: 113, requirement: "经销商板块 / 项目管理 / 项目查询 / 查询说明 / 只能输入信息查询，不支持列表浏览", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=projects&state=search", fields: ["查询说明（文本提示）"], actions: ["只能输入信息查询，不支持列表浏览"], states: ["不展示列表，只提供搜索入口"], evidence: ["docx:table-row-113", "src/services/project.ts", "tests/v32-requirements.test.ts#row-113"], status: "complete-local" },
  { sourceRow: 114, requirement: "经销商板块 / 项目管理 / 项目查询 / 船名/SN号/客户姓名 / 输入关键词查询", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=projects&state=search", fields: ["船名/SN号/客户姓名（文本输入框）"], actions: ["输入关键词查询"], states: ["可查询基本信息、安装、售后情况", "模糊匹配，展示项目详情卡片"], evidence: ["docx:table-row-114", "src/services/project.ts", "tests/v32-requirements.test.ts#row-114"], status: "complete-local" },
  { sourceRow: 115, requirement: "经销商板块 / 售后 / 物料申请 / 物料名称 / 选择申请物料", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=materials", fields: ["物料名称（下拉选择）"], actions: ["选择申请物料"], states: ["必填", "从物料表读取"], evidence: ["docx:table-row-115", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-115"], status: "complete-local" },
  { sourceRow: 116, requirement: "经销商板块 / 售后 / 物料申请 / 申请数量 / 输入申请数量", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=materials", fields: ["申请数量（数字输入框）"], actions: ["输入申请数量"], states: ["必填，正整数", "保存到售后申请表"], evidence: ["docx:table-row-116", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-116"], status: "complete-local" },
  { sourceRow: 117, requirement: "经销商板块 / 售后 / 物料申请 / 申请原因 / 说明申请原因", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=materials", fields: ["申请原因（文本域）"], actions: ["说明申请原因"], states: ["选填", "保存备注字段"], evidence: ["docx:table-row-117", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-117"], status: "complete-local" },
  { sourceRow: 118, requirement: "经销商板块 / 售后 / 审批进度 / 申请状态 / 显示审批状态", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=materials", fields: ["申请状态（状态标签）"], actions: ["显示审批状态"], states: ["待审批/已审批/已拒绝", "从售后申请表读取"], evidence: ["docx:table-row-118", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-118"], status: "complete-local" },
  { sourceRow: 119, requirement: "经销商板块 / 售后 / 审批进度 / 发货状态 / 显示物料发货状态", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=materials", fields: ["发货状态（状态标签）"], actions: ["显示物料发货状态"], states: ["待发货/已发货/已签收", "从物流表读取"], evidence: ["docx:table-row-119", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-119"], status: "partial" },
  { sourceRow: 120, requirement: "经销商板块 / 售后 / 快递公司 / 显示快递公司名称", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=logistics", fields: ["快递公司（标签）"], actions: ["显示快递公司名称"], states: ["从物流表读取", "后台发货时选择的快递公司"], evidence: ["docx:table-row-120", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-120"], status: "complete-local" },
  { sourceRow: 121, requirement: "经销商板块 / 售后 / 物流单号 / 显示快递单号（可复制）", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=logistics", fields: ["物流单号（文本）"], actions: ["显示快递单号（可复制）"], states: ["点击复制", "从物流表读取"], evidence: ["docx:table-row-121", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-121"], status: "complete-local" },
  { sourceRow: 122, requirement: "经销商板块 / 售后 / 物流详情 / 查看详细物流轨迹", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=logistics", fields: ["物流详情（按钮）"], actions: ["查看详细物流轨迹"], states: ["已发货状态显示", "跳转物流详情页，调用快递100接口展示轨迹"], evidence: ["docx:table-row-122", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-122"], status: "simulated-local" },
  { sourceRow: 123, requirement: "经销商板块 / 售后 / 物料名称 / 查询物料采购价", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=materials&state=price-search", fields: ["物料名称（文本输入框）"], actions: ["查询物料采购价"], states: ["模糊匹配物料表"], evidence: ["docx:table-row-123", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-123"], status: "complete-local" },
  { sourceRow: 124, requirement: "采购价 / 显示物料采购价", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=materials&state=price-search", fields: ["采购价（金额文本）"], actions: ["显示物料采购价"], states: ["仅经销商可见", "按权限控制显示"], evidence: ["docx:table-row-124", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-124"], status: "complete-local" },
  { sourceRow: 125, requirement: "售后概况 / 当月统计 / 统计当月售后数量", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=dealerAnalytics", fields: ["当月统计（数字/图表）"], actions: ["统计当月售后数量"], states: ["一级代理含二级代理数据", "汇总当月售后申请表数据"], evidence: ["docx:table-row-125", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-125"], status: "complete-local" },
  { sourceRow: 126, requirement: "年度统计 / 统计年度售后情况", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=dealerAnalytics", fields: ["年度统计（数字/图表）"], actions: ["统计年度售后情况"], states: ["一级代理含二级代理数据", "按年度汇总，展示趋势图"], evidence: ["docx:table-row-126", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-126"], status: "complete-local" },
  { sourceRow: 127, requirement: "物流追踪 / 物流单号 / 展示所有物流订单", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=shipments", fields: ["物流单号（列表）"], actions: ["展示所有物流订单"], states: ["按时间倒序", "查询当前经销商关联物流记录"], evidence: ["docx:table-row-127", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-127"], status: "complete-local" },
  { sourceRow: 128, requirement: "快递公司 / 快递公司名称", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=shipments", fields: ["快递公司（文本）"], actions: ["快递公司名称"], states: ["从物流表读取"], evidence: ["docx:table-row-128", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-128"], status: "complete-local" },
  { sourceRow: 129, requirement: "物流状态 / 当前物流状态", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=shipments", fields: ["物流状态（状态标签）"], actions: ["当前物流状态"], states: ["运输中/已签收/异常", "从快递100接口获取"], evidence: ["docx:table-row-129", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-129"], status: "simulated-local" },
  { sourceRow: 130, requirement: "物流轨迹 / 详细物流轨迹时间线", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=logistics", fields: ["物流轨迹（时间线）"], actions: ["详细物流轨迹时间线"], states: ["调用快递100接口", "正序排列展示轨迹"], evidence: ["docx:table-row-130", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-130"], status: "simulated-local" },
  { sourceRow: 131, requirement: "经销商设备管理 / 设备分配 / 设备列表（未分配） / 展示总代名下未分配的机器", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=devices&state=unassigned", fields: ["设备列表（未分配）（列表）"], actions: ["展示总代名下未分配的机器"], states: ["总代可见所有未分配设备", "查询设备表中归属为总代的设备"], evidence: ["docx:table-row-131", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-131"], status: "complete-local" },
  { sourceRow: 132, requirement: "经销商设备管理 / 设备分配 / 分配按钮 / 总代将设备分配给二级经销商", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=transfers&mode=dealer-assignment", fields: ["分配按钮（按钮）"], actions: ["总代将设备分配给二级经销商"], states: ["分配后设备归属变更", "更新设备表经销商ID字段"], evidence: ["docx:table-row-132", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-132", "tests/e2e/dealer-workspace.spec.ts"], status: "integration-required" },
  { sourceRow: 133, requirement: "经销商设备管理 / 分配记录 / 记录每次分配的设备、来源、去向、时间", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=transfers", fields: ["分配记录（表格）"], actions: ["记录每次分配的设备、来源、去向、时间"], states: ["写入分配日志表"], evidence: ["docx:table-row-133", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-133"], status: "partial" },
  { sourceRow: 134, requirement: "经销商设备管理 / 归属判断 / 设备在谁名下，谁处理该设备的售后", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=transfers", fields: ["归属判断（系统逻辑）"], actions: ["设备在谁名下，谁处理该设备的售后"], states: ["总代可见名下所有设备，二级仅见被分配的设备", "根据设备表经销商ID匹配报修单"], evidence: ["docx:table-row-134", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-134"], status: "partial" },
  { sourceRow: 135, requirement: "经销商设备管理 / 调货申请 / 经销商申请将设备调给其他经销商", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=transfers&mode=reallocation", fields: ["调货申请（按钮）"], actions: ["经销商申请将设备调给其他经销商"], states: ["需平台审核", "写入调货申请表，状态待审核"], evidence: ["docx:table-row-135", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-135"], status: "partial" },
  { sourceRow: 136, requirement: "经销商设备管理 / 调货审批 / 平台审核调货申请", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=transfers", fields: ["调货审批（表格）"], actions: ["平台审核调货申请"], states: ["通过后设备归属变更", "更新设备表经销商ID"], evidence: ["docx:table-row-136", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-136"], status: "demo-exception" },
  { sourceRow: 137, requirement: "调货记录 / 记录每次调货的设备、来源、去向、审核人、时间", roles: ["dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=transfers", fields: ["调货记录（表格）"], actions: ["记录每次调货的设备、来源、去向、审核人、时间"], states: ["写入调货日志表"], evidence: ["docx:table-row-137", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-137"], status: "complete-local" },
  { sourceRow: 138, requirement: "国内支付 / 微信支付 / 国内用户通过微信支付完成订单付款", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=payment", fields: ["微信支付（支付组件）"], actions: ["国内用户通过微信支付完成订单付款"], states: ["需微信商户号", "调用微信支付SDK"], evidence: ["docx:table-row-138", "src/services/adapters.ts", "tests/v32-requirements.test.ts#row-138"], status: "simulated-local" },
  { sourceRow: 139, requirement: "支付宝支付 / 国内用户通过支付宝完成订单付款", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=payment", fields: ["支付宝支付（支付组件）"], actions: ["国内用户通过支付宝完成订单付款"], states: ["需支付宝商户号", "调用支付宝SDK"], evidence: ["docx:table-row-139", "src/services/adapters.ts", "tests/v32-requirements.test.ts#row-139"], status: "simulated-local" },
  { sourceRow: 140, requirement: "海外支付 / PayPal / 海外用户通过PayPal完成付款", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=payment", fields: ["PayPal（支付组件）"], actions: ["海外用户通过PayPal完成付款"], states: ["需PayPal商户号", "调用PayPal API"], evidence: ["docx:table-row-140", "src/services/adapters.ts", "tests/v32-requirements.test.ts#row-140"], status: "simulated-local" },
  { sourceRow: 141, requirement: "Apple Pay / 海外用户通过Apple Pay完成付款", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=payment", fields: ["Apple Pay（支付组件）"], actions: ["海外用户通过Apple Pay完成付款"], states: ["iOS端支持", "调用Apple Pay API"], evidence: ["docx:table-row-141", "src/services/adapters.ts", "tests/v32-requirements.test.ts#row-141"], status: "simulated-local" },
  { sourceRow: 142, requirement: "Google Pay / 海外用户通过Google Pay完成付款", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/process/index?scenario=payment", fields: ["Google Pay（支付组件）"], actions: ["海外用户通过Google Pay完成付款"], states: ["Android端支持", "调用Google Pay API"], evidence: ["docx:table-row-142", "src/services/adapters.ts", "tests/v32-requirements.test.ts#row-142"], status: "simulated-local" },
  { sourceRow: 143, requirement: "支付记录 / 支付历史 / 查看历史支付订单", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=payments", fields: ["支付历史（列表）"], actions: ["查看历史支付订单"], states: ["查询支付记录表"], evidence: ["docx:table-row-143", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-143"], status: "complete-local" },
  { sourceRow: 144, requirement: "补充模块 / 投诉功能 / 投诉入口 / 用户提交投诉信息，平台或代理商处理", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=complaint", fields: ["投诉入口（按钮）"], actions: ["用户提交投诉信息，平台或代理商处理"], states: ["需登录后显示，可附带订单/设备SN", "保存到投诉表，推送给总部管理员"], evidence: ["docx:table-row-144", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-144"], status: "partial" },
  { sourceRow: 145, requirement: "跨区售后转移 / 转移申请 / 用户或经销商发起售后跨区转移申请", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/form?entity=tickets&category=transfer", fields: ["转移申请（按钮）"], actions: ["用户或经销商发起售后跨区转移申请"], states: ["需原代理商确认+目标代理商接收", "保存转移工单，通知各方确认"], evidence: ["docx:table-row-145", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-145"], status: "partial" },
  { sourceRow: 146, requirement: "转单（留言升级） / 转单入口 / 客服留言可转单给代理商或总部处理", roles: ["user", "dealerAdmin", "dealerStaff"], route: "/pages/manage/list?entity=tickets&state=transfer-selector&id=ticket-04", fields: ["转单入口（按钮）"], actions: ["客服留言可转单给代理商或总部处理"], states: ["客户手动选择转单对象", "更新留言归属，推送通知给目标对象"], evidence: ["docx:table-row-146", "src/services/workflow.ts", "tests/v32-requirements.test.ts#row-146"], status: "complete-local" },
]

export const v32PlatformRequirements: RequirementCase[] = [
  { sourceRow: 4, requirement: '国内版/海外版启动标识决定地图、认证与服务区域', roles: ['guest', 'user', 'dealerAdmin', 'dealerStaff'], route: '/pages/auth/login?state=region', fields: ['版本标识（系统逻辑）'], actions: ['读取 VITE_APP_REGION 并选择区域能力'], states: ['CN', 'GLOBAL'], evidence: ['docx:table-row-004', 'src/config/region.ts', 'tests/v32-requirements.test.ts#row-004'], status: 'complete-local' },
  { sourceRow: 5, requirement: '国内版支持手机号与微信认证，数据存储在国内服务器', roles: ['guest'], route: '/pages/auth/login?region=CN', fields: ['国内版特性（说明）'], actions: ['手机号认证', '微信认证'], states: ['本地手机号认证可用', '微信流程可本地模拟', '国内服务器需生产环境接入'], evidence: ['docx:table-row-005', 'src/services/auth.ts', 'src/services/adapters.ts', 'tests/v32-requirements.test.ts#row-005'], status: 'integration-required' },
  { sourceRow: 6, requirement: '海外版支持邮箱与 Google 认证，数据存储于美国并使用其他地区 CDN', roles: ['guest'], route: '/pages/auth/login?region=GLOBAL', fields: ['海外版特性（说明）'], actions: ['邮箱认证', 'Google 认证'], states: ['本地邮箱认证可用', 'Google 流程可本地模拟', '海外服务器与 CDN 需生产环境接入'], evidence: ['docx:table-row-006', 'src/services/auth.ts', 'src/services/adapters.ts', 'tests/v32-requirements.test.ts#row-006'], status: 'integration-required' },
  { sourceRow: 7, requirement: '游客模式 / 支持游客模式进入', roles: ['guest'], route: '/pages/auth/login?state=region', fields: ['游客入口（按钮）'], actions: ['以游客身份进入公开首页、地图和帮助'], states: ['公开设备只读', '控制、添加、航点写入和售后提交触发 X02 登录提示'], evidence: ['xlsx:APP端功能列表:row-007', 'src/pages/auth/login.vue', 'tests/v32-requirements.test.ts#row-007'], status: 'complete-local' },
]

const routeScore = (requiredRoute: string, designRoute: string) => {
  const [requiredPath, requiredQuery = ''] = requiredRoute.split('?')
  const [designPath, designQuery = ''] = designRoute.split('?')
  if (requiredPath !== designPath) return -1
  if (requiredRoute === designRoute) return 100
  const expected = new URLSearchParams(requiredQuery)
  const actual = new URLSearchParams(designQuery)
  let score = 10
  expected.forEach((value, key) => { score += actual.get(key) === value ? 8 : actual.has(key) ? -3 : 0 })
  return score
}

for (const item of [...v32PlatformRequirements, ...v32RequirementCoverage]) {
  item.sourceSheet = 'APP端功能列表'
  item.sourceText = item.requirement
  item.evidence = item.evidence.map((value) => value.replace(/^docx:table-row-/, 'xlsx:APP端功能列表:row-'))
  if (item.status === 'partial') item.status = 'integration-required'
  const scored = designCaseRegistry.map((designCase) => ({ designCase, score: routeScore(item.route, designCase.route) })).filter(({ score }) => score >= 0).sort((left, right) => right.score - left.score)
  const bestScore = scored[0]?.score
  item.uiCaseIds = bestScore === undefined ? [] : [...new Set(scored.filter(({ score }) => score === bestScore).map(({ designCase }) => designCase.id))]
  item.uiAssertions = [...item.fields, ...item.actions, ...item.states]
  item.conclusion = item.status === 'source-blank' ? 'source-blank' : item.status === 'integration-required' || item.status === 'demo-exception' ? 'integration-required' : 'covered'
}

export const v32RequirementSource = 'outputs/requirements_excel_v3_2/鲨鱼妹妹项目需求-APP端功能列表_V3.2.xlsx#APP端功能列表!A4:H146'
