import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(here, '..')
const sourceRoot = resolve(projectRoot, '..', 'assest')
const targetRoot = resolve(projectRoot, 'src', 'static', 'assest')
const manifest = JSON.parse(await readFile(resolve(sourceRoot, 'manifest.json'), 'utf8'))

await rm(targetRoot, { recursive: true, force: true })
await mkdir(targetRoot, { recursive: true })
for (const folder of ['icons', 'brand', 'backgrounds']) {
  await cp(resolve(sourceRoot, folder), resolve(targetRoot, folder), { recursive: true })
}
await cp(resolve(sourceRoot, 'manifest.json'), resolve(targetRoot, 'manifest.json'))
const tones = ['default', 'muted', 'disabled', 'inverse', 'brand', 'brand-strong', 'success', 'warning', 'warning-strong', 'danger', 'accent', 'offline', 'support']
const iconIndex = Object.fromEntries(manifest.icons.map((icon) => [icon.name, {
  defaultTone: icon.variants.find((variant) => variant.color === icon.dominantColor)?.tone || icon.variants[0].tone,
  tones: icon.variants.map((variant) => variant.tone),
}]))
const assetKey = (file) => file.split('/').pop().replace(/\.png$/i, '').replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
const brandIndex = Object.fromEntries(manifest.brand.map((asset) => [assetKey(asset.file), `/static/assest/${asset.file}`]))
const backgroundIndex = Object.fromEntries(manifest.backgrounds.map((asset) => [assetKey(asset.file), `/static/assest/${asset.file}`]))
const generatedIndex = `// Generated by scripts/sync-assets.mjs. Do not edit manually.\n` +
  `const bundledIconAssets = import.meta.glob('../static/assest/icons/variants/*.png', { eager: true, import: 'default', query: '?url' }) as Record<string, string>\n` +
  `const bundledBrandAssets = import.meta.glob('../static/assest/brand/*.png', { eager: true, import: 'default', query: '?url' }) as Record<string, string>\n` +
  `const bundledBackgroundAssets = import.meta.glob('../static/assest/backgrounds/*.png', { eager: true, import: 'default', query: '?url' }) as Record<string, string>\n\n` +
  `export const iconTones = ${JSON.stringify(tones)} as const\n` +
  `export type IconTone = typeof iconTones[number]\n` +
  `export const iconAssets = ${JSON.stringify(iconIndex, null, 2)} as const\n` +
  `export type IconName = keyof typeof iconAssets\n\n` +
  `const brandAssetPaths = ${JSON.stringify(brandIndex, null, 2)} as const\n` +
  `const backgroundAssetPaths = ${JSON.stringify(backgroundIndex, null, 2)} as const\n` +
  `export const brandAssets = Object.fromEntries(Object.entries(brandAssetPaths).map(([key, path]) => [key, bundledBrandAssets[\`../static\${path.slice('/static'.length)}\`] || path])) as Record<keyof typeof brandAssetPaths, string>\n` +
  `export const backgroundAssets = Object.fromEntries(Object.entries(backgroundAssetPaths).map(([key, path]) => [key, bundledBackgroundAssets[\`../static\${path.slice('/static'.length)}\`] || path])) as Record<keyof typeof backgroundAssetPaths, string>\n\n` +
  `export function resolveIconTone(name: string, tone?: IconTone): IconTone {\n` +
  `  const icon = iconAssets[name as IconName]\n` +
  `  if (!icon) return 'default'\n` +
  `  if (tone && (icon.tones as readonly string[]).includes(tone)) return tone\n` +
  `  if (!tone && (icon.tones as readonly string[]).includes('default')) return 'default'\n` +
  `  return icon.defaultTone\n` +
  `}\n\n` +
  `export function resolveIconAsset(name: string, tone?: IconTone): string {\n` +
  `  const icon = iconAssets[name as IconName]\n` +
  `  const fileName = icon ? \`\${name}--\${resolveIconTone(name, tone)}.png\` : 'circle-help--default.png'\n` +
  `  return bundledIconAssets[\`../static/assest/icons/variants/\${fileName}\`] || \`/static/assest/icons/variants/\${fileName}\`\n` +
  `}\n`
await writeFile(resolve(projectRoot, 'src', 'config', 'iconAssets.ts'), generatedIndex, 'utf8')
console.log(`Synced ${manifest.counts.productionFiles} production assets to src/static/assest`)
